Research System
Terasology/MasterOfOreon pull request #24
Opened 2018-07-13 10:26 UTC by Naman-sopho

Includes: 
- Construction of a new Laboratory building.
- A new Research Task which can be added by taking a book out of the Laboratory building's bookcase and placing it in the building's pedestal.
- Performing the research task. This requires the blocks mentioned in the recipe to be present in the building's chest.
- Addition of fence blocks around a area after task assignment.

Requires this https://github.com/Terasology/Books/pull/16 to be merged.

### How to test
- Select an area and assign the Laboratory construction task. The area should be resized according to the size of the building and fences be placed around this new area.
- After construction execute the command `give oreonplant0` and place the obtained items in Laboratory chest(required by the research task).
- Take the book out of bookcase(consists of the recipe which would be used for the research) and place it in the Pedestal. Oreon should perform the research task which adds a Cookie Crop block to the chest.

2018-07-14 02:23 UTC, mkienenb requested changes
Looks pretty good.   Just needs a few more constants.

2018-07-14 02:23 UTC, mkienenb commented on src/main/java/org/terasology/research/ResearchSystem.java
> +                    String recipePrefabName = "";
You could move this section into a well-named method to make the code easier to read.

2018-07-14 02:23 UTC, mkienenb commented on src/main/java/org/terasology/research/ResearchSystem.java
> +        taskComponent.taskRegion = buildingComponent.boundingRegions.get(16);
magic number -- what does 16 mean? Use a constant.

2018-07-14 02:23 UTC, mkienenb commented on src/main/java/org/terasology/taskSystem/TaskManagementSystem.java
> +        Block block = blockManager.getBlock("Fences:fence.0");
Seems like this should be a constant.

2018-07-14 02:23 UTC, mkienenb commented on src/main/java/org/terasology/taskSystem/TaskManagementSystem.java
> +            block = blockManager.getBlock("Core:Torch.TOP");
Seems like this should be a constant.

2018-07-14 02:23 UTC, mkienenb commented on src/main/java/org/terasology/taskSystem/TaskManagementSystem.java
> +                buildingPrefab = prefabManager.getPrefab("MasterOfOreon:inn");
Seems like this should be a constant.

2018-07-14 02:23 UTC, mkienenb commented on src/main/java/org/terasology/taskSystem/TaskManagementSystem.java
> +            default:
Seems like this should be a constant.

2018-07-21 20:37 UTC, merged

2018-07-21 20:39 UTC, Cervator commented
Tested out, can confirm the research system appears to work 👍 Nice work there.

While testing this and the other PR (and occasionally overall) I've noticed a variety of quality issues and smaller quirks that aren't necessarily linked to this PR. I added some as card to the project board, would be nice to get some of those addressed and focus some on stabilizing stuff further :-)