Add upgraded laboratory and storage
Terasology/MasterOfOreon pull request #36
Opened 2018-11-10 01:50 UTC by FieryPhoenix909

I renamed the 'laboratory' buildings to 'lab' and 'storage' to 'storehouse' so that upgraded buildings with proper naming conventions/types could be added.
![screenshot 13](https://user-images.githubusercontent.com/23224432/48296097-d8cb5e00-e460-11e8-9df6-274098ff0ef1.png)
### **^Upgraded storage**
![screenshot 14](https://user-images.githubusercontent.com/23224432/48296098-d8cb5e00-e460-11e8-9d81-0a2816ca0a69.png)
![screenshot 15](https://user-images.githubusercontent.com/23224432/48296099-d8cb5e00-e460-11e8-9578-e91a1abe260f.png)
### **^Inside of upgraded lab**
![screenshot 16](https://user-images.githubusercontent.com/23224432/48296100-d8cb5e00-e460-11e8-8170-7d8f1b0500ed.png)
### **^Upgraded lab**

2018-12-23 12:37 UTC, Naman-sopho commented
Great job! The new building and its upgrade work correctly.
But there are still a few bugs to address:
- The Laboratory is added to the holding after the upgrade, but the old instance is not removed. So the count on the overview screen becomes erroneous.
- After the upgrade, the Laboratory is not correctly "initialized" i.e. its Pedestal block is not registered. So, after the upgrade a research task cannot be added from this Laboratory.

2020-04-11 12:43 UTC, skaldarnar requested changes
I'll merge this into a new branch and apply the required changes.

2020-04-11 12:43 UTC, skaldarnar commented on assets/prefabs/structureTemplates/types/laboratory1.prefab
> +    "StructureTemplateType" : {}
File should be renamed to `laboratoryLevel1` according to existing naming schemes.

2020-04-11 12:43 UTC, skaldarnar commented on assets/prefabs/structureTemplates/types/storage1.prefab
> +    "StructureTemplateType" : {}
File should be renamed to `storageLevel1` according to existing naming schemes.

2020-04-11 14:23 UTC, closed without merging