Remove dependency on the Miniion module.
Terasology/MasterOfOreon pull request #5
Opened 2018-05-07 19:04 UTC by Naman-sopho

MasterOfOreon used the Miniion module for `TaskManagementSystem` which assigned tasks to the Oreons and spawning Oreons from the menu. 
To do further, Spawning using `Portals` and a new Task management system.

2018-05-07 23:06 UTC, mkienenb commented on src/main/java/org/terasology/managerInterface/nui/ManagerInterfaceHUDElement.java
>          EntityManager entityManager = CoreRegistry.get(EntityManager.class);
Note that all references to CoreRegistry.get(class) need to be replaced with either @In annotations (best idea) or context.get(class) codes (find-and-replace).  You'll probably need an @In annotation to pull in a context.

2018-05-09 02:37 UTC, mkienenb commented
Still looks good to me, although you might want to verify that your @In values are actually non-null.

2018-05-13 00:28 UTC, vampcat requested changes
One minor request for renaming.

2018-05-13 00:28 UTC, vampcat commented on src/main/java/org/terasology/managerInterface/nui/ManagerInterfaceHUDElement.java
> +    private PrefabManager prefMan;
Change this to `prefabManager` please.
Unless it's a variable like `i` for a loop counter, I would recommend that you stick with descriptive names.

2018-05-14 15:09 UTC, closed without merging